// Copyright (c) 2024 ETH Zurich and University of Bologna.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0/
//
// Authors:
// - Philippe Sauter <phsauter@iis.ee.ethz.ch>

#include "simple_cnt.h"
#include "print.h"
#include "conv1d.h"
#include "conv_accel.h"
#include "data.h" // input data and golden output generated by datagen.py

uint32_t R_sw[K_NUM * R_ROWS * R_COLS] = {0};
uint32_t R_hw[K_NUM * R_ROWS * R_COLS] = {0};

int main() {
    // Initialize the hardware accelerator
    // TODO: implement this function in `conv_accel.c`
    conv_accel_init();
    
    // Start the performance counter
    simple_cnt_enable();


    // HARDWARE-ACCELERATED 1D CONVOLUTION
    // -----------------------------------
    // Get performance counter value
    t_start = simple_cnt_get_value(); // DO NOT CHANGE THIS LINE
    
    // Launch hardware-accelerated 1D convolution
    // TODO: implement this function in `conv1d.c`
    conv1d_hw(A, F, R_hw, INPUT_LEN, INPUT_CH, K_NUM);
    
    // Get performance counter value
    t_end = simple_cnt_get_value(); // DO NOT CHANGE THIS LINE
    printf("HW cycles: %u\n", t_end - t_start); // DO NOT CHANGE THIS LINE

    
    // SOFTWARE 1D CONVOLUTION
    // -----------------------
    // Get performance counter value
    t_start = simple_cnt_get_value(); // DO NOT CHANGE THIS LINE

    // Launch software 1D convolution
    conv1d_sw(A, F, R_sw, INPUT_LEN, INPUT_CH, K_NUM);

    // Get performance counter value
    t_end = simple_cnt_get_value(); // DO NOT CHANGE THIS LINE
    printf("CPU cycles: %u\n", t_end - t_start); // DO NOT CHANGE THIS LINE
    

    // RESULT CHECKING
    // ---------------
    // Compare the CPU output data with the golden output
    if (memcmp(R_sw, R, R_SIZE) != 0) {
        printf("CPU result mismatch!\n");
        return -1;
    }

    // Compare the HW output data with the golden output
    if (memcmp(R_hw, R, R_SIZE) != 0) {
        printf("HW result mismatch!\n");
        return -1;
    }

    // Exit with no errors
    printf("Success!\n");

    return 0;
}
