
+define+TARGET_SYNTHESIS
+define+TARGET_TEST
+define+TARGET_VERILATOR
+incdir+/foss/designs/rtl/user_domain/conv1d/../../obi/include
+incdir+/foss/designs/rtl/user_domain/conv1d/../../register_interface/include
+incdir+/foss/designs/rtl/user_domain/conv1d/hw/vendor/pulp-platform-common-cells/include
+incdir+/foss/designs/rtl/user_domain/conv1d/hw/vendor/pulp-platform-register-interface/include
/foss/designs/rtl/user_domain/conv1d/hw/packages/conv1d_obi_pkg.sv
/foss/designs/rtl/user_domain/conv1d/hw/packages/conv1d_reg_pkg.sv
/foss/designs/rtl/user_domain/conv1d/hw/packages/conv1d_sram_pkg.sv
/foss/designs/rtl/user_domain/conv1d/hw/control-reg/rtl/conv1d_control_reg_pkg.sv
/foss/designs/rtl/user_domain/conv1d/hw/vendor/pulp-platform-common-cells/src/cf_math_pkg.sv
/foss/designs/rtl/user_domain/conv1d/../../obi/obi_pkg.sv
/foss/designs/rtl/user_domain/conv1d/../../croc_pkg.sv
/foss/designs/rtl/user_domain/conv1d/hw/control-reg/rtl/conv1d_control_reg_top.sv
/foss/designs/rtl/user_domain/conv1d/hw/control-reg/conv1d_control_reg.sv
/foss/designs/rtl/user_domain/conv1d/hw/conv1d.sv
/foss/designs/rtl/user_domain/conv1d/hw/conv1d_obi.sv
/foss/designs/rtl/user_domain/conv1d/hw/obi_sram_shim.sv
/foss/designs/rtl/user_domain/conv1d/hw/src/accelerator.sv
/foss/designs/rtl/user_domain/conv1d/hw/src/accumulator.sv
/foss/designs/rtl/user_domain/conv1d/hw/src/adder.sv
/foss/designs/rtl/user_domain/conv1d/hw/src/branch.sv
/foss/designs/rtl/user_domain/conv1d/hw/src/datapath.sv
/foss/designs/rtl/user_domain/conv1d/hw/src/downcounter_3bit.sv
/foss/designs/rtl/user_domain/conv1d/hw/src/final_sum.sv
/foss/designs/rtl/user_domain/conv1d/hw/src/fsm_qalc.sv
/foss/designs/rtl/user_domain/conv1d/hw/src/fsm_tot.sv
/foss/designs/rtl/user_domain/conv1d/hw/src/multiplier.sv
/foss/designs/rtl/user_domain/conv1d/hw/src/mux2to1.sv
/foss/designs/rtl/user_domain/conv1d/hw/src/mux4to1.sv
/foss/designs/rtl/user_domain/conv1d/hw/src/mux5to1.sv
/foss/designs/rtl/user_domain/conv1d/hw/src/register.sv
/foss/designs/rtl/user_domain/conv1d/hw/src/upcounter_2bit.sv
/foss/designs/rtl/user_domain/conv1d/hw/vendor/pulp-platform-tech-cells-generic/src/rtl/tc_sram.sv
/foss/designs/rtl/user_domain/conv1d/hw/vendor/pulp-platform-register-interface/vendor/lowrisc_opentitan/src/prim_subreg_arb.sv
/foss/designs/rtl/user_domain/conv1d/hw/vendor/pulp-platform-register-interface/vendor/lowrisc_opentitan/src/prim_subreg_ext.sv
/foss/designs/rtl/user_domain/conv1d/hw/vendor/pulp-platform-register-interface/vendor/lowrisc_opentitan/src/prim_subreg_shadow.sv
/foss/designs/rtl/user_domain/conv1d/hw/vendor/pulp-platform-register-interface/vendor/lowrisc_opentitan/src/prim_subreg.sv

+define+TARGET_SYNTHESIS
+define+TARGET_TEST
+define+TARGET_VERILATOR
+incdir+/foss/designs/rtl/user_domain/conv1d/../../obi/include
+incdir+/foss/designs/rtl/user_domain/conv1d/../../register_interface/include
+incdir+/foss/designs/rtl/user_domain/conv1d/hw/vendor/pulp-platform-common-cells/include
+incdir+/foss/designs/rtl/user_domain/conv1d/hw/vendor/pulp-platform-register-interface/include
/foss/designs/rtl/user_domain/conv1d/hw/simulation/conv1d_sram_wrapper.sv
/foss/designs/rtl/user_domain/conv1d/tb/conv1d_tb_wrapper.sv

